version: 1.0.{build}

environment:
  coverity_token:
    secure: WhwjmR5SADRwFkBX06kWsl1SNdovILcyr0hlXerox6I=
  coverity_email:
    secure: vBiSHFruVmaa7NLHJWzvHL4CHgOQ+vzDMYmR2LshjLM=
    
install:
- ps: cinst curl -y

build_script:
- ps: |
    & cov-build.exe --dir cov-int msbuild "$Env:APPVEYOR_BUILD_FOLDER\PeerNet.sln" `
      /verbosity:normal `
      /p:Configuration=Release `
      /p:Platform=x86 `
      /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
      
on_success:
  7z a "PeerNet.zip" "cov-int"
  
  curl --form token=%coverity_token% \
    --form email=%coverity_email% \
    --form file=@PeerNet.zip \
    --form version="1.0" \
    --form description="AppVeyor Build." \
    https://scan.coverity.com/builds?project=kklouzal%2FPeerNet
  
notifications:
- provider: Email
  to:
    - kyle.klouzal@gmail.com
  on_build_status_changed: true
