version: 1.0.{build}

image: Visual Studio 2017

environment:
  COVERITY_TOKEN:
    secure: WhwjmR5SADRwFkBX06kWsl1SNdovILcyr0hlXerox6I=
  COVERITY_EMAIL:
    secure: vBiSHFruVmaa7NLHJWzvHL4CHgOQ+vzDMYmR2LshjLM=
    
install:
- ps: cinst curl -y
- cmd: cd C:\ && git clone https://github.com/Microsoft/vcpkg.git && cd vcpkg && bootstrap-vcpkg.bat && cd %APPVEYOR_BUILD_FOLDER%

build_script:
- cmd: C:\vcpkg\vcpkg install cereal:x32-windows zstd:x32-windows
- cmd: C:\vcpkg\vcpkg integrate install
- ps: |
    & cov-build.exe --dir cov-int msbuild "$Env:APPVEYOR_BUILD_FOLDER\PeerNet.sln" `
      /verbosity:normal `
      /p:Configuration=Release `
      /p:Platform=x32 `
      /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
      
on_success:
  7z a "PeerNet.zip" "cov-int"
  
  curl --form token=%COVERITY_TOKEN% --form email=%COVERITY_EMAIL% --form file=@PeerNet.zip --form version="1.0" --form description="AppVeyor Build." https://scan.coverity.com/projects/10224/builds
  
notifications:
- provider: Email
  to:
    - kyle.klouzal@gmail.com
  on_build_status_changed: true
